### Numpy

**Alunos**:

- **Pedro Henrique Paz Sobral**
- **Wodson Fernando Oliveira da Silva**
- **Roselene Maria Botelho Rocha**

In [14]:
import numpy as np

1 - Utilize o método `numpy.info` para obter informações do método `numpy.add`.

In [15]:
# Insira a resposta abaixo.
# o método numpy.info se comporta como o help()
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

2 - Utilize a função *range* do python para criar automaticamente uma lista de números variando de 0 até 15.

In [16]:
# Insira a resposta abaixo.
lista = []
for i in range(0,16):
  lista.append(i)
print(lista)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


3 - Converta a lista criada para um objeto do tipo numpy array.

In [17]:
# Insira a resposta abaixo.
array = np.array(lista)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

4 - Crie um  novo array equivalente ao anterior utilizando diretamente os recursos do numpy.

In [18]:
# Insira a resposta abaixo.
new_array = np.array(range(16), dtype=int)
print(new_array)

# ou

new_array2= np.arange(0,16)
print(new_array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


5 - A partir do último array utilizado anteriormente, realize os seguintes procedimentos:

1. Exiba o formato atual do array.
2. Altere o formato para (4, 4).
3. Exiba novamente o formato do array após redimensioná-lo.

In [19]:
# Insira a resposta abaixo.

# Passo 1 - shape
print(new_array2.shape)

# Passo 2 e passo 3.reshape
teste = new_array2.reshape((4,4))
print(teste.shape)




(16,)
(4, 4)


6 - Compute a média, mediana e o desvio padrão do array resultante da questão anterior.

In [20]:
# Insira a resposta abaixo.
media = np.mean(teste)
mediana = np.median(teste)
desvio = np.std(teste)


print(f'sua média: {media} \n sua mediana: {mediana} \n seu desvio padrão: {desvio}')

sua média: 7.5 
 sua mediana: 7.5 
 seu desvio padrão: 4.6097722286464435


7 - Crie uma cópia do array atual  e transforme todos os números em valores negativos.

In [21]:
# Insira a resposta abaixo.

array_negativo = teste * -1
print(array_negativo)

[[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


8 - Realize os seguintes procedimentos:

1. Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.

2. Concatene horizontalmente (*column-wise*) o array resultante do passo 1 com ele mesmo.

3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

Como fazer?

> Analise a documentação das funções `stack`, `hstack` e `dstack` da biblioteca numpy.

In [22]:
# Insira a resposta abaixo.

print(f' Array positivo \n \n {teste} \n ')
print(f'Array negativo: \n \n {array_negativo}\n')

# Passo 1 -
 # concatenar (ou seja juntar), uma matriz sob a outra vertical( uma em cima da outra) -
 # Concatene verticalmente (*row-wise*) o array de números positivos com o array de números negativos.
row_wise = np.vstack((teste, array_negativo))

print(f' Row Wise  \n \n {row_wise}')


 Array positivo 
 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
 
Array negativo: 
 
 [[  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]

 Row Wise  
 
 [[  0   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [  0  -1  -2  -3]
 [ -4  -5  -6  -7]
 [ -8  -9 -10 -11]
 [-12 -13 -14 -15]]


In [23]:
#Passo 2
#Concatene horizontalmente column-wise o array resultante do passo 1 com ele mesmo.
column_wise = np.hstack((row_wise, row_wise))
print(column_wise)

[[  0   1   2   3   0   1   2   3]
 [  4   5   6   7   4   5   6   7]
 [  8   9  10  11   8   9  10  11]
 [ 12  13  14  15  12  13  14  15]
 [  0  -1  -2  -3   0  -1  -2  -3]
 [ -4  -5  -6  -7  -4  -5  -6  -7]
 [ -8  -9 -10 -11  -8  -9 -10 -11]
 [-12 -13 -14 -15 -12 -13 -14 -15]]


In [24]:
#Passo 3
#3. Concatene em profundidade três cópias do array resultante do passo anterior, exibindo o formato final.

deep_stack = np.dstack((row_wise,row_wise,row_wise))
print(deep_stack)

[[[  0   0   0]
  [  1   1   1]
  [  2   2   2]
  [  3   3   3]]

 [[  4   4   4]
  [  5   5   5]
  [  6   6   6]
  [  7   7   7]]

 [[  8   8   8]
  [  9   9   9]
  [ 10  10  10]
  [ 11  11  11]]

 [[ 12  12  12]
  [ 13  13  13]
  [ 14  14  14]
  [ 15  15  15]]

 [[  0   0   0]
  [ -1  -1  -1]
  [ -2  -2  -2]
  [ -3  -3  -3]]

 [[ -4  -4  -4]
  [ -5  -5  -5]
  [ -6  -6  -6]
  [ -7  -7  -7]]

 [[ -8  -8  -8]
  [ -9  -9  -9]
  [-10 -10 -10]
  [-11 -11 -11]]

 [[-12 -12 -12]
  [-13 -13 -13]
  [-14 -14 -14]
  [-15 -15 -15]]]


In [25]:
deep_stack.shape

(8, 4, 3)

9 - Utilize o array do passo 1 da questão anterior e transforme os valores da segunda e terceira colunas em 1.

In [47]:
# Insira a resposta abaixo.
nova= teste

In [27]:
um_um =teste[:,1:3] /  teste[:,1:3]
print(um_um)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [28]:
col_1 =teste[:,0:1]
print(col_1)

[[ 0]
 [ 4]
 [ 8]
 [12]]


In [29]:
col_4 = teste[:,3:4]
print(col_4)

[[ 3]
 [ 7]
 [11]
 [15]]


In [30]:
juntar = np.hstack((col_1,um_um,col_4))
print(juntar)

[[ 0.  1.  1.  3.]
 [ 4.  1.  1.  7.]
 [ 8.  1.  1. 11.]
 [12.  1.  1. 15.]]


In [31]:
 teste[:, 1:3] = 1 #pesquisado
print(teste)

[[ 0  1  1  3]
 [ 4  1  1  7]
 [ 8  1  1 11]
 [12  1  1 15]]


10 - Adicione 2.5 a todos os valores presentes no array resultante da etapa anterior.

In [32]:
juntar.shape

(4, 4)

In [33]:
dois_meio = np.full((4,4), 2.5)
print(dois_meio)

[[2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]]


In [34]:
soma_dois_meio = dois_meio + teste
print(soma_dois_meio)

[[ 2.5  3.5  3.5  5.5]
 [ 6.5  3.5  3.5  9.5]
 [10.5  3.5  3.5 13.5]
 [14.5  3.5  3.5 17.5]]


11 - Realize as seguintes operações:
1. Crie uma matriz com valor 3 em todas as posições com dimensionalidade (4, 2).
2. Crie uma matriz identidade de dimensionalidade (4, 4).
3. Compute o produto entre a transposta da primeira matriz e a matriz identidade, apresentando o resultado final.

In [35]:
# Insira a resposta abaixo.

# Passo 1
quatro_20 = np.full((2,4), 3)
transposta = quatro_20.T
print(transposta)


[[3 3]
 [3 3]
 [3 3]
 [3 3]]


In [36]:
# Passo 2
quatro_quatro = np.eye(4)
print(quatro_quatro)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [37]:
expansao = np.tile(transposta, (1, 2))

In [38]:
# Passo 3
resultado = expansao * quatro_quatro
print(resultado)

[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]


12 - Realize as seguintes operações:
1. Crie uma nova matriz de valores inteiros de 25 até 49 com dimensionalidade (5,5).
2. Crie uma nova matriz com valores uniformemente espaçados entre 0 e 1 e defina a sua dimensionalidade em (5,1).
3. Concatene horizontalmente as duas matrizes criadas anteriormente.

In [39]:
# Insira a resposta abaixo.

# Passo 1
vinte5 = np.arange(25,50).reshape(5,5)

print(vinte5)


[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [40]:
# Passo 2
aleatorio = np.random.random((5,1))
aleatorio

array([[0.86144684],
       [0.19617683],
       [0.37827282],
       [0.93646759],
       [0.29225752]])

In [41]:
concatenado = np.hstack((vinte5,aleatorio))
print(concatenado)

[[25.         26.         27.         28.         29.          0.86144684]
 [30.         31.         32.         33.         34.          0.19617683]
 [35.         36.         37.         38.         39.          0.37827282]
 [40.         41.         42.         43.         44.          0.93646759]
 [45.         46.         47.         48.         49.          0.29225752]]


13 - Crie uma nova matriz com dimensionalidade (5,1) com números uniformemente espaçados utilizando um espaço logarítmico ao invés de um espaço linear.

In [56]:
help(np.logspace)

Help on _ArrayFunctionDispatcher in module numpy:

logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)
    Return numbers spaced evenly on a log scale.

    In linear space, the sequence starts at ``base ** start``
    (`base` to the power of `start`) and ends with ``base ** stop``
    (see `endpoint` below).

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.25.0
        Non-scalar 'base` is now supported

    Parameters
    ----------
    start : array_like
        ``base ** start`` is the starting value of the sequence.
    stop : array_like
        ``base ** stop`` is the final value of the sequence, unless `endpoint`
        is False.  In that case, ``num + 1`` values are spaced over the
        interval in log-space, of which all but the last (a sequence of
        length `num`) are returned.
    num : integer, optional
        Number of samples to generate.  Default is 50.
    endpoint : boo

In [60]:
começo = 0
parada = 1
num = 5
espaçada = np.logspace(começo, parada, 5).reshape(5, 1)


print(espaçada)

[[ 1.        ]
 [ 1.77827941]
 [ 3.16227766]
 [ 5.62341325]
 [10.        ]]


14 - Crie uma função que receba um array e adicione uma borda composta de zeros nos quatro lados do array. Utilize o array resultante da questão anterior para testar o método criado.

In [77]:
# Insira a resposta abaixo.
def borda_zeros(matriz):
  bordado = np.pad(matriz, pad_width=1, mode='constant', constant_values=0) #pesquisei a função np.pad
  return bordado


In [78]:
borda_zeros(espaçada)

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.        ,  1.77827941,  0.        ],
       [ 0.        ,  3.16227766,  0.        ],
       [ 0.        ,  5.62341325,  0.        ],
       [ 0.        , 10.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

15 - Crie um array de 36 números aleatórios oriundos de uma distribuição normal. Exiba o valor máximo, mínimo, a média e o desvio padrão desse array.

In [75]:
# Insira a resposta abaixo.
array36 = np.random.normal(0,1, (6, 6))
print(array36)

max36 = np.max(array36)
min36 = np.min(array36)
med36 = np.mean(array36)
dp36 = np.std(array36)

print(f'\n seu ponto max: {max36:.3f} \n seu ponto min: {min36:.3f} \n sua média: {med36:.3f} \n seu desvio padrão: {dp36:.3f}')

[[-0.62699781  0.69665358  0.83072018  0.17560879  0.68494219  0.27736855]
 [-2.36716096 -1.87085318 -1.03310644 -0.42290242 -0.91261419 -2.39896053]
 [-0.3345874  -1.63876382  0.76106684  0.72305426 -0.28288658 -0.29757476]
 [-0.63702604 -0.26891443 -0.77210238  0.82184575  0.50011354  1.70554667]
 [-0.48940999 -0.27334666 -0.4740225  -1.35615767 -0.4375977  -0.65331674]
 [ 1.01029518  3.50390449  0.62069721 -1.10462072  1.94132552 -0.45137739]]

 seu ponto max: 3.504 
 seu ponto min: -2.399 
 sua média: -0.135 
 seu desvio padrão: 1.170
